junit4 assignment
SahilBabbar12/JUnit_Assignment pull request #1
Opened 2023-04-08 10:27 UTC by SahilBabbar12

2023-04-09 12:48 UTC, anup0060 requested changes

2023-04-09 12:48 UTC, anup0060 commented on JUnit4/src/main/java/com/knoldus/StringOperations.java
> +        Scanner input = new Scanner(System.in);
there should be one space of either of equal

2023-04-09 12:48 UTC, anup0060 commented on JUnit4/src/test/java/StringUtilsTest.java
> +    public void testReverseString_Test1(){
_Test1 _Test2 , why all methods with these suffixes 

_shouldReverse_givenCorrectInput -- like this, we need to have the name that reflects scenario as suffix.

2023-04-11 16:42 UTC, SahilBabbar12 reviewed
I have made the changes suggested by you. Please review it again.

2023-04-12 17:35 UTC, anup0060 approved these changes

2023-04-12 17:35 UTC, merged