junit 5 assignment
SahilBabbar12/JUnit_Assignment pull request #2
Opened 2023-04-08 11:04 UTC by SahilBabbar12

2023-04-09 12:53 UTC, anup0060 requested changes

2023-04-09 12:53 UTC, anup0060 commented on JUnit5/src/test/java/com/knoldus/PersonTest.java
> +        person.setName(null);
poor naming 

testGetName_whenNameNull

2023-04-09 12:53 UTC, anup0060 commented on JUnit5/src/test/java/com/knoldus/PersonTest.java
> +
why line gap

2023-04-09 12:53 UTC, anup0060 commented on JUnit5/src/test/java/com/knoldus/PersonTest.java
> +    public void setAgeTest_ifAgeIsZero() {
use words - should, given, when in suffix , instead of if.

2023-04-11 18:33 UTC, SahilBabbar12 reviewed
I have made the changes suggested by you. please review it again.

2023-04-12 17:33 UTC, anup0060 approved these changes

2023-04-12 17:33 UTC, merged